[package]
name = "subby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcp_auth = "0.7"
anyhow = "1"
reqwest = { version = "0.11", features = ["json", "brotli"] }
serde = "1"
